"""Initial migration

Revision ID: 887c1246226f
Revises: 
Create Date: 2025-03-16 19:30:37.728204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887c1246226f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
